---
# Add mymachine to /etc/hosts targeting your IP!
version: '3'

services:

  zookeeper:
    # See also: https://hub.docker.com/r/bitnami/zookeeper
    image: bitnami/zookeeper:latest
    expose:
      - '2181'
      - '2888'
      - '3888'
    ports:
      - "22181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    # See also: https://hub.docker.com/r/bitnami/kafka
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://mymachine:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'

  consumer:
    image: kafka-consumer:latest
    depends_on:
      - kafka
    environment:
      KAFKA_NUM_PARTITIONS: 3

  producer:
    image: kafka-producer:latest
    depends_on:
      - kafka

